replicaCount: 1

image:
  repository: ""  # Will be set by Jenkins pipeline
  tag: ""         # Will be set by Jenkins pipeline
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30500

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Flask app specific configuration
app:
  name: rs-school-devops
  env: production